version: '3'
services:
  currency-formatter:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/react-docker:delegated
      - /node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_CURRENCY_API_URL=
      - REACT_APP_CURRENCY_API_KEY=
    container_name: currency-formatter
