import axios from 'axios';

import { currencyApiConfig } from 'config';

class CurrencyApiClient {
  private axiosInstance;

  constructor() {
    this.axiosInstance = axios.create({
      baseURL: currencyApiConfig.currencyApiUrl,
      params: {
        apikey: currencyApiConfig.currencyApiKey,
      },
    });
  }


  async currencies(params: { currencies?: string } = {}) {
    // const { data } = await this.axiosInstance.get<GetCurrenciesListResponse>(
    //   `/currencies`,
    //   {
    //     params,
    //   },
    // );

  const parsedAuthResponse = 'sd'.split(';').reduce((acc, val) => {
    const [key, value] = val.split('=');
    return {...acc, [key.trim()]: value}
}, {})

    const data = {
      data: {
        AFN: {
          symbol: 'Af',
          name: 'Afghan Afghani',
          symbol_native: '؋',
          decimal_digits: 0,
          rounding: 0,
          code: 'AFN',
          name_plural: 'Afghan Afghanis',
        },
        ALL: {
          symbol: 'ALL',
          name: 'Albanian Lek',
          symbol_native: 'Lek',
          decimal_digits: 0,
          rounding: 0,
          code: 'ALL',
          name_plural: 'Albanian lekë',
        },
        AMD: {
          symbol: 'AMD',
          name: 'Armenian Dram',
          symbol_native: 'դր.',
          decimal_digits: 0,
          rounding: 0,
          code: 'AMD',
          name_plural: 'Armenian drams',
        },
        ANG: {
          symbol: 'ƒ',
          name: 'NL Antillean Guilder',
          symbol_native: 'NAƒ',
          decimal_digits: 2,
          rounding: 0,
          code: 'ANG',
          icon_name: 'ang',
          name_plural: 'NL Antillean Guilders',
        },
        AOA: {
          symbol: 'Kz',
          name: 'Angolan Kwanza',
          symbol_native: 'Kz',
          decimal_digits: 2,
          rounding: 0,
          code: 'AOA',
          icon_name: 'aoa',
          name_plural: 'Angolan Kwanza',
        },
        ARS: {
          symbol: 'AR$',
          name: 'Argentine Peso',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'ARS',
          name_plural: 'Argentine pesos',
        },
        AUD: {
          symbol: 'AU$',
          name: 'Australian Dollar',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'AUD',
          name_plural: 'Australian dollars',
        },
        AWG: {
          symbol: 'Afl.',
          name: 'Aruban Florin',
          symbol_native: 'Afl.',
          decimal_digits: 2,
          rounding: 0,
          code: 'AWG',
          icon_name: 'awg',
          name_plural: 'Aruban Florin',
        },
        AZN: {
          symbol: 'man.',
          name: 'Azerbaijani Manat',
          symbol_native: 'ман.',
          decimal_digits: 2,
          rounding: 0,
          code: 'AZN',
          name_plural: 'Azerbaijani manats',
        },
        BAM: {
          symbol: 'KM',
          name: 'Bosnia-Herzegovina Convertible Mark',
          symbol_native: 'KM',
          decimal_digits: 2,
          rounding: 0,
          code: 'BAM',
          name_plural: 'Bosnia-Herzegovina convertible marks',
        },
        BBD: {
          symbol: 'Bds$',
          name: 'Barbadian Dollar',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'BBD',
          icon_name: 'bbd',
          name_plural: 'Barbadian Dollars',
        },
        BDT: {
          symbol: 'Tk',
          name: 'Bangladeshi Taka',
          symbol_native: '৳',
          decimal_digits: 2,
          rounding: 0,
          code: 'BDT',
          name_plural: 'Bangladeshi takas',
        },
        BGN: {
          symbol: 'BGN',
          name: 'Bulgarian Lev',
          symbol_native: 'лв.',
          decimal_digits: 2,
          rounding: 0,
          code: 'BGN',
          name_plural: 'Bulgarian leva',
        },
        BHD: {
          symbol: 'BD',
          name: 'Bahraini Dinar',
          symbol_native: 'د.ب.‏',
          decimal_digits: 3,
          rounding: 0,
          code: 'BHD',
          name_plural: 'Bahraini dinars',
        },
        BIF: {
          symbol: 'FBu',
          name: 'Burundian Franc',
          symbol_native: 'FBu',
          decimal_digits: 0,
          rounding: 0,
          code: 'BIF',
          name_plural: 'Burundian francs',
        },
        BMD: {
          symbol: 'BD$',
          name: 'Bermudan Dollar',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'BMD',
          icon_name: 'bmd',
          name_plural: 'Bermudan Dollars',
        },
        BND: {
          symbol: 'BN$',
          name: 'Brunei Dollar',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'BND',
          name_plural: 'Brunei dollars',
        },
        BOB: {
          symbol: 'Bs',
          name: 'Bolivian Boliviano',
          symbol_native: 'Bs',
          decimal_digits: 2,
          rounding: 0,
          code: 'BOB',
          name_plural: 'Bolivian bolivianos',
        },
        BRL: {
          symbol: 'R$',
          name: 'Brazilian Real',
          symbol_native: 'R$',
          decimal_digits: 2,
          rounding: 0,
          code: 'BRL',
          name_plural: 'Brazilian reals',
        },
        BSD: {
          symbol: 'B$',
          name: 'Bahamian Dollar',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'BSD',
          icon_name: 'bsd',
          name_plural: 'Bahamian Dollars',
        },
        BTN: {
          symbol: 'Nu.',
          name: 'Bhutanese Ngultrum',
          symbol_native: 'Nu.',
          decimal_digits: 2,
          rounding: 0,
          code: 'BTN',
          icon_name: 'btn',
          name_plural: 'Bhutanese Ngultrum',
        },
        BWP: {
          symbol: 'BWP',
          name: 'Botswanan Pula',
          symbol_native: 'P',
          decimal_digits: 2,
          rounding: 0,
          code: 'BWP',
          name_plural: 'Botswanan pulas',
        },
        BYN: {
          symbol: 'Br',
          name: 'Belarusian ruble',
          symbol_native: 'Br',
          decimal_digits: 2,
          rounding: 0,
          code: 'BYN',
          name_plural: 'Belarusian rubles',
        },
        BYR: {
          symbol: 'BYR',
          name: 'Belarusian Ruble',
          symbol_native: 'BYR',
          decimal_digits: 0,
          rounding: 0,
          code: 'BYR',
          name_plural: 'Belarusian rubles',
        },
        BZD: {
          symbol: 'BZ$',
          name: 'Belize Dollar',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'BZD',
          name_plural: 'Belize dollars',
        },
        CAD: {
          symbol: 'CA$',
          name: 'Canadian Dollar',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'CAD',
          name_plural: 'Canadian dollars',
        },
        CDF: {
          symbol: 'CDF',
          name: 'Congolese Franc',
          symbol_native: 'FrCD',
          decimal_digits: 2,
          rounding: 0,
          code: 'CDF',
          name_plural: 'Congolese francs',
        },
        CHF: {
          symbol: 'CHF',
          name: 'Swiss Franc',
          symbol_native: 'CHF',
          decimal_digits: 2,
          rounding: 0,
          code: 'CHF',
          name_plural: 'Swiss francs',
        },
        CLF: {
          symbol: 'UF',
          name: 'Unidad de Fomento',
          symbol_native: 'UF',
          decimal_digits: 2,
          rounding: 0,
          code: 'CLF',
          name_plural: 'Unidad de Fomentos',
        },
        CLP: {
          symbol: 'CL$',
          name: 'Chilean Peso',
          symbol_native: '$',
          decimal_digits: 0,
          rounding: 0,
          code: 'CLP',
          name_plural: 'Chilean pesos',
        },
        CNY: {
          symbol: 'CN¥',
          name: 'Chinese Yuan',
          symbol_native: 'CN¥',
          decimal_digits: 2,
          rounding: 0,
          code: 'CNY',
          name_plural: 'Chinese yuan',
        },
        COP: {
          symbol: 'CO$',
          name: 'Coombian Peso',
          symbol_native: '$',
          decimal_digits: 0,
          rounding: 0,
          code: 'COP',
          name_plural: 'Colombian pesos',
        },
        CRC: {
          symbol: '₡',
          name: 'Costa Rican Colón',
          symbol_native: '₡',
          decimal_digits: 0,
          rounding: 0,
          code: 'CRC',
          name_plural: 'Costa Rican colóns',
        },
        CUC: {
          symbol: 'CUC$',
          name: 'Cuban Convertible Peso',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'CUC',
          icon_name: 'cuc',
          name_plural: 'Cuban Convertible Peso',
        },
        CUP: {
          symbol: '$MN',
          name: 'Cuban Peso',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'CUP',
          icon_name: 'cup',
          name_plural: 'Cuban Peso',
        },
        CVE: {
          symbol: 'CV$',
          name: 'Cape Verdean Escudo',
          symbol_native: 'CV$',
          decimal_digits: 2,
          rounding: 0,
          code: 'CVE',
          name_plural: 'Cape Verdean escudos',
        },
        CZK: {
          symbol: 'Kč',
          name: 'Czech Republic Koruna',
          symbol_native: 'Kč',
          decimal_digits: 2,
          rounding: 0,
          code: 'CZK',
          name_plural: 'Czech Republic korunas',
        },
        DJF: {
          symbol: 'Fdj',
          name: 'Djiboutian Franc',
          symbol_native: 'Fdj',
          decimal_digits: 0,
          rounding: 0,
          code: 'DJF',
          name_plural: 'Djiboutian francs',
        },
        DKK: {
          symbol: 'Dkr',
          name: 'Danish Krone',
          symbol_native: 'kr',
          decimal_digits: 2,
          rounding: 0,
          code: 'DKK',
          name_plural: 'Danish kroner',
        },
        DOP: {
          symbol: 'RD$',
          name: 'Dominican Peso',
          symbol_native: 'RD$',
          decimal_digits: 2,
          rounding: 0,
          code: 'DOP',
          name_plural: 'Dominican pesos',
        },
        DZD: {
          symbol: 'DA',
          name: 'Algerian Dinar',
          symbol_native: 'د.ج.‏',
          decimal_digits: 2,
          rounding: 0,
          code: 'DZD',
          name_plural: 'Algerian dinars',
        },
        EGP: {
          symbol: 'EGP',
          name: 'Egyptian Pound',
          symbol_native: 'ج.م.‏',
          decimal_digits: 2,
          rounding: 0,
          code: 'EGP',
          name_plural: 'Egyptian pounds',
        },
        ERN: {
          symbol: 'Nfk',
          name: 'Eritrean Nakfa',
          symbol_native: 'Nfk',
          decimal_digits: 2,
          rounding: 0,
          code: 'ERN',
          name_plural: 'Eritrean nakfas',
        },
        ETB: {
          symbol: 'Br',
          name: 'Ethiopian Birr',
          symbol_native: 'Br',
          decimal_digits: 2,
          rounding: 0,
          code: 'ETB',
          name_plural: 'Ethiopian birrs',
        },
        EUR: {
          symbol: '€',
          name: 'Euro',
          symbol_native: '€',
          decimal_digits: 2,
          rounding: 0,
          code: 'EUR',
          name_plural: 'Euros',
        },
        FJD: {
          symbol: 'FJ$',
          name: 'Fijian Dollar',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'FJD',
          icon_name: 'fjd',
          name_plural: 'Fijian Dollar',
        },
        FKP: {
          symbol: 'FK£',
          name: 'Falkland Islands Pound',
          symbol_native: '£',
          decimal_digits: 2,
          rounding: 0,
          code: 'FKP',
          icon_name: 'fkp',
          name_plural: 'Falkland Islands Pound',
        },
        GBP: {
          symbol: '£',
          name: 'British Pound Sterling',
          symbol_native: '£',
          decimal_digits: 2,
          rounding: 0,
          code: 'GBP',
          name_plural: 'British pounds sterling',
        },
        GEL: {
          symbol: 'GEL',
          name: 'Georgian Lari',
          symbol_native: 'GEL',
          decimal_digits: 2,
          rounding: 0,
          code: 'GEL',
          name_plural: 'Georgian laris',
        },
        GGP: {
          symbol: '£',
          name: 'Guernsey pound',
          symbol_native: '£',
          decimal_digits: 2,
          rounding: 0,
          code: 'GGP',
          name_plural: 'Guernsey pounds',
        },
        GHS: {
          symbol: 'GH₵',
          name: 'Ghanaian Cedi',
          symbol_native: 'GH₵',
          decimal_digits: 2,
          rounding: 0,
          code: 'GHS',
          name_plural: 'Ghanaian cedis',
        },
        GIP: {
          symbol: '£',
          name: 'Gibraltar Pound',
          symbol_native: '£',
          decimal_digits: 2,
          rounding: 0,
          code: 'GIP',
          icon_name: 'gip',
          name_plural: 'Gibraltar Pounds',
        },
        GMD: {
          symbol: 'D',
          name: 'Gambian Dalasi',
          symbol_native: 'D',
          decimal_digits: 2,
          rounding: 0,
          code: 'GMD',
          icon_name: 'gmd',
          name_plural: 'Gambian Dalasi',
        },
        GNF: {
          symbol: 'FG',
          name: 'Guinean Franc',
          symbol_native: 'FG',
          decimal_digits: 0,
          rounding: 0,
          code: 'GNF',
          name_plural: 'Guinean francs',
        },
        GTQ: {
          symbol: 'GTQ',
          name: 'Guatemalan Quetzal',
          symbol_native: 'Q',
          decimal_digits: 2,
          rounding: 0,
          code: 'GTQ',
          name_plural: 'Guatemalan quetzals',
        },
        GYD: {
          symbol: 'G$',
          name: 'Guyanaese Dollar',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'GYD',
          icon_name: 'gyd',
          name_plural: 'Guyanaese Dollar',
        },
        HKD: {
          symbol: 'HK$',
          name: 'Hong Kong Dollar',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'HKD',
          name_plural: 'Hong Kong dollars',
        },
        HNL: {
          symbol: 'HNL',
          name: 'Honduran Lempira',
          symbol_native: 'L',
          decimal_digits: 2,
          rounding: 0,
          code: 'HNL',
          name_plural: 'Honduran lempiras',
        },
        HRK: {
          symbol: 'kn',
          name: 'Croatian Kuna',
          symbol_native: 'kn',
          decimal_digits: 2,
          rounding: 0,
          code: 'HRK',
          name_plural: 'Croatian kunas',
        },
        HTG: {
          symbol: 'G',
          name: 'Haitian Gourde',
          symbol_native: 'G',
          decimal_digits: 2,
          rounding: 0,
          code: 'HTG',
          icon_name: 'htg',
          name_plural: 'Haitian Gourde',
        },
        HUF: {
          symbol: 'Ft',
          name: 'Hungarian Forint',
          symbol_native: 'Ft',
          decimal_digits: 0,
          rounding: 0,
          code: 'HUF',
          name_plural: 'Hungarian forints',
        },
        IDR: {
          symbol: 'Rp',
          name: 'Indonesian Rupiah',
          symbol_native: 'Rp',
          decimal_digits: 0,
          rounding: 0,
          code: 'IDR',
          name_plural: 'Indonesian rupiahs',
        },
        ILS: {
          symbol: '₪',
          name: 'Israeli New Sheqel',
          symbol_native: '₪',
          decimal_digits: 2,
          rounding: 0,
          code: 'ILS',
          name_plural: 'Israeli new sheqels',
        },
        IMP: {
          symbol: '£',
          name: 'Manx pound',
          symbol_native: '£',
          decimal_digits: 2,
          rounding: 0,
          code: 'IMP',
          name_plural: 'Manx pounds',
        },
        INR: {
          symbol: 'Rs',
          name: 'Indian Rupee',
          symbol_native: 'টকা',
          decimal_digits: 2,
          rounding: 0,
          code: 'INR',
          name_plural: 'Indian rupees',
        },
        IQD: {
          symbol: 'IQD',
          name: 'Iraqi Dinar',
          symbol_native: 'د.ع.‏',
          decimal_digits: 0,
          rounding: 0,
          code: 'IQD',
          name_plural: 'Iraqi dinars',
        },
        IRR: {
          symbol: 'IRR',
          name: 'Iranian Rial',
          symbol_native: '﷼',
          decimal_digits: 0,
          rounding: 0,
          code: 'IRR',
          name_plural: 'Iranian rials',
        },
        ISK: {
          symbol: 'Ikr',
          name: 'Icelandic Króna',
          symbol_native: 'kr',
          decimal_digits: 0,
          rounding: 0,
          code: 'ISK',
          name_plural: 'Icelandic krónur',
        },
        JEP: {
          symbol: '£',
          name: 'Jersey pound',
          symbol_native: '£',
          decimal_digits: 2,
          rounding: 0,
          code: 'JEP',
          name_plural: 'Jersey pound',
        },
        JMD: {
          symbol: 'J$',
          name: 'Jamaican Dollar',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'JMD',
          name_plural: 'Jamaican dollars',
        },
        JOD: {
          symbol: 'JD',
          name: 'Jordanian Dinar',
          symbol_native: 'د.أ.‏',
          decimal_digits: 3,
          rounding: 0,
          code: 'JOD',
          name_plural: 'Jordanian dinars',
        },
        JPY: {
          symbol: '¥',
          name: 'Japanese Yen',
          symbol_native: '￥',
          decimal_digits: 0,
          rounding: 0,
          code: 'JPY',
          name_plural: 'Japanese yen',
        },
        KES: {
          symbol: 'Ksh',
          name: 'Kenyan Shilling',
          symbol_native: 'Ksh',
          decimal_digits: 2,
          rounding: 0,
          code: 'KES',
          name_plural: 'Kenyan shillings',
        },
        KGS: {
          symbol: 'KGS',
          name: 'Kyrgystani Som',
          symbol_native: 'KGS',
          decimal_digits: 2,
          rounding: 0,
          code: 'KGS',
          icon_name: 'kgs',
          name_plural: 'Kyrgystani Som',
        },
        KHR: {
          symbol: 'KHR',
          name: 'Cambodian Riel',
          symbol_native: '៛',
          decimal_digits: 2,
          rounding: 0,
          code: 'KHR',
          name_plural: 'Cambodian riels',
        },
        KMF: {
          symbol: 'CF',
          name: 'Comorian Franc',
          symbol_native: 'FC',
          decimal_digits: 0,
          rounding: 0,
          code: 'KMF',
          name_plural: 'Comorian francs',
        },
        KPW: {
          symbol: '₩',
          name: 'North Korean Won',
          symbol_native: '₩',
          decimal_digits: 2,
          rounding: 0,
          code: 'KPW',
          icon_name: 'kpw',
          name_plural: 'North Korean Won',
        },
        KRW: {
          symbol: '₩',
          name: 'South Korean Won',
          symbol_native: '₩',
          decimal_digits: 0,
          rounding: 0,
          code: 'KRW',
          name_plural: 'South Korean won',
        },
        KWD: {
          symbol: 'KD',
          name: 'Kuwaiti Dinar',
          symbol_native: 'د.ك.‏',
          decimal_digits: 3,
          rounding: 0,
          code: 'KWD',
          name_plural: 'Kuwaiti dinars',
        },
        KYD: {
          symbol: 'CI$',
          name: 'Cayman Islands Dollar',
          symbol_native: '$‏',
          decimal_digits: 2,
          rounding: 0,
          code: 'KYD',
          icon_name: 'kyd',
          name_plural: 'Cayman Islands Dollar',
        },
        KZT: {
          symbol: 'KZT',
          name: 'Kazakhstani Tenge',
          symbol_native: 'тңг.',
          decimal_digits: 2,
          rounding: 0,
          code: 'KZT',
          name_plural: 'Kazakhstani tenges',
        },
        LAK: {
          symbol: '₭N',
          name: 'Laotian Kip',
          symbol_native: '₭‏‏',
          decimal_digits: 0,
          rounding: 0,
          code: 'LAK',
          name_plural: 'Laotian Kip',
        },
        LBP: {
          symbol: 'LB£',
          name: 'Lebanese Pound',
          symbol_native: 'ل.ل.‏',
          decimal_digits: 0,
          rounding: 0,
          code: 'LBP',
          name_plural: 'Lebanese pounds',
        },
        LKR: {
          symbol: 'SLRs',
          name: 'Sri Lankan Rupee',
          symbol_native: 'SL Re',
          decimal_digits: 2,
          rounding: 0,
          code: 'LKR',
          name_plural: 'Sri Lankan rupees',
        },
        LRD: {
          symbol: 'LD$',
          name: 'Liberian Dollar',
          symbol_native: 'L$',
          decimal_digits: 2,
          rounding: 0,
          code: 'LRD',
          icon_name: 'lrd',
          name_plural: 'Liberian Dollar',
        },
        LSL: {
          symbol: 'L',
          name: 'Lesotho Loti',
          symbol_native: 'M',
          decimal_digits: 2,
          rounding: 0,
          code: 'LSL',
          icon_name: 'lsl',
          name_plural: 'Lesotho Loti',
        },
        LTL: {
          symbol: 'Lt',
          name: 'Lithuanian Litas',
          symbol_native: 'Lt',
          decimal_digits: 2,
          rounding: 0,
          code: 'LTL',
          name_plural: 'Lithuanian litai',
        },
        LVL: {
          symbol: 'Ls',
          name: 'Latvian Lats',
          symbol_native: 'Ls',
          decimal_digits: 2,
          rounding: 0,
          code: 'LVL',
          name_plural: 'Latvian lati',
        },
        LYD: {
          symbol: 'LD',
          name: 'Libyan Dinar',
          symbol_native: 'د.ل.‏',
          decimal_digits: 3,
          rounding: 0,
          code: 'LYD',
          name_plural: 'Libyan dinars',
        },
        MAD: {
          symbol: 'MAD',
          name: 'Moroccan Dirham',
          symbol_native: 'د.م.‏',
          decimal_digits: 2,
          rounding: 0,
          code: 'MAD',
          name_plural: 'Moroccan dirhams',
        },
        MDL: {
          symbol: 'MDL',
          name: 'Moldovan Leu',
          symbol_native: 'MDL',
          decimal_digits: 2,
          rounding: 0,
          code: 'MDL',
          name_plural: 'Moldovan lei',
        },
        MGA: {
          symbol: 'MGA',
          name: 'Malagasy Ariary',
          symbol_native: 'MGA',
          decimal_digits: 0,
          rounding: 0,
          code: 'MGA',
          name_plural: 'Malagasy Ariaries',
        },
        MKD: {
          symbol: 'MKD',
          name: 'Macedonian Denar',
          symbol_native: 'MKD',
          decimal_digits: 2,
          rounding: 0,
          code: 'MKD',
          name_plural: 'Macedonian denari',
        },
        MMK: {
          symbol: 'MMK',
          name: 'Myanma Kyat',
          symbol_native: 'K',
          decimal_digits: 0,
          rounding: 0,
          code: 'MMK',
          name_plural: 'Myanma kyats',
        },
        MNT: {
          symbol: '₮',
          name: 'Mongolian Tugrik',
          symbol_native: '₮',
          decimal_digits: 2,
          rounding: 0,
          code: 'MNT',
          icon_name: 'mnt',
          name_plural: 'Mongolian Tugrik',
        },
        MOP: {
          symbol: 'MOP$',
          name: 'Macanese Pataca',
          symbol_native: 'MOP$',
          decimal_digits: 2,
          rounding: 0,
          code: 'MOP',
          name_plural: 'Macanese patacas',
        },
        MRO: {
          symbol: 'UM',
          name: 'Mauritanian ouguiya',
          symbol_native: 'UM',
          decimal_digits: 2,
          rounding: 0,
          code: 'MRO',
          name_plural: 'Mauritanian ouguiyas',
        },
        MUR: {
          symbol: 'MURs',
          name: 'Mauritian Rupee',
          symbol_native: 'MURs',
          decimal_digits: 0,
          rounding: 0,
          code: 'MUR',
          name_plural: 'Mauritian rupees',
        },
        MVR: {
          symbol: 'MRf',
          name: 'Maldivian Rufiyaa',
          symbol_native: 'Rf',
          decimal_digits: 2,
          rounding: 0,
          code: 'MVR',
          name_plural: 'Maldivian Rufiyaa',
        },
        MWK: {
          symbol: 'MK',
          name: 'Malawian Kwacha',
          symbol_native: 'MK',
          decimal_digits: 2,
          rounding: 0,
          code: 'MWK',
          icon_name: 'mwk',
          name_plural: 'Malawian Kwacha',
        },
        MXN: {
          symbol: 'MX$',
          name: 'Mexican Peso',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'MXN',
          name_plural: 'Mexican pesos',
        },
        MYR: {
          symbol: 'RM',
          name: 'Malaysian Ringgit',
          symbol_native: 'RM',
          decimal_digits: 2,
          rounding: 0,
          code: 'MYR',
          name_plural: 'Malaysian ringgits',
        },
        MZN: {
          symbol: 'MTn',
          name: 'Mozambican Metical',
          symbol_native: 'MTn',
          decimal_digits: 2,
          rounding: 0,
          code: 'MZN',
          name_plural: 'Mozambican meticals',
        },
        NAD: {
          symbol: 'N$',
          name: 'Namibian Dollar',
          symbol_native: 'N$',
          decimal_digits: 2,
          rounding: 0,
          code: 'NAD',
          name_plural: 'Namibian dollars',
        },
        NGN: {
          symbol: '₦',
          name: 'Nigerian Naira',
          symbol_native: '₦',
          decimal_digits: 2,
          rounding: 0,
          code: 'NGN',
          name_plural: 'Nigerian nairas',
        },
        NIO: {
          symbol: 'C$',
          name: 'Nicaraguan Córdoba',
          symbol_native: 'C$',
          decimal_digits: 2,
          rounding: 0,
          code: 'NIO',
          name_plural: 'Nicaraguan córdobas',
        },
        NOK: {
          symbol: 'Nkr',
          name: 'Norwegian Krone',
          symbol_native: 'kr',
          decimal_digits: 2,
          rounding: 0,
          code: 'NOK',
          name_plural: 'Norwegian kroner',
        },
        NPR: {
          symbol: 'NPRs',
          name: 'Nepalese Rupee',
          symbol_native: 'नेरू',
          decimal_digits: 2,
          rounding: 0,
          code: 'NPR',
          name_plural: 'Nepalese rupees',
        },
        NZD: {
          symbol: 'NZ$',
          name: 'New Zealand Dollar',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'NZD',
          name_plural: 'New Zealand dollars',
        },
        OMR: {
          symbol: 'OMR',
          name: 'Omani Rial',
          symbol_native: 'ر.ع.‏',
          decimal_digits: 3,
          rounding: 0,
          code: 'OMR',
          name_plural: 'Omani rials',
        },
        PAB: {
          symbol: 'B/.',
          name: 'Panamanian Balboa',
          symbol_native: 'B/.',
          decimal_digits: 2,
          rounding: 0,
          code: 'PAB',
          name_plural: 'Panamanian balboas',
        },
        PEN: {
          symbol: 'S/.',
          name: 'Peruvian Nuevo Sol',
          symbol_native: 'S/.',
          decimal_digits: 2,
          rounding: 0,
          code: 'PEN',
          name_plural: 'Peruvian nuevos soles',
        },
        PGK: {
          symbol: 'K',
          name: 'Papua New Guinean Kina',
          symbol_native: 'K',
          decimal_digits: 2,
          rounding: 0,
          code: 'PGK',
          icon_name: 'pgk',
          name_plural: 'Papua New Guinean Kina',
        },
        PHP: {
          symbol: '₱',
          name: 'Philippine Peso',
          symbol_native: '₱',
          decimal_digits: 2,
          rounding: 0,
          code: 'PHP',
          name_plural: 'Philippine pesos',
        },
        PKR: {
          symbol: 'PKRs',
          name: 'Pakistani Rupee',
          symbol_native: '₨',
          decimal_digits: 0,
          rounding: 0,
          code: 'PKR',
          name_plural: 'Pakistani rupees',
        },
        PLN: {
          symbol: 'zł',
          name: 'Polish Zloty',
          symbol_native: 'zł',
          decimal_digits: 2,
          rounding: 0,
          code: 'PLN',
          name_plural: 'Polish zlotys',
        },
        PYG: {
          symbol: '₲',
          name: 'Paraguayan Guarani',
          symbol_native: '₲',
          decimal_digits: 0,
          rounding: 0,
          code: 'PYG',
          name_plural: 'Paraguayan guaranis',
        },
        QAR: {
          symbol: 'QR',
          name: 'Qatari Rial',
          symbol_native: 'ر.ق.‏',
          decimal_digits: 2,
          rounding: 0,
          code: 'QAR',
          name_plural: 'Qatari rials',
        },
        RON: {
          symbol: 'RON',
          name: 'Romanian Leu',
          symbol_native: 'RON',
          decimal_digits: 2,
          rounding: 0,
          code: 'RON',
          name_plural: 'Romanian lei',
        },
        RSD: {
          symbol: 'din.',
          name: 'Serbian Dinar',
          symbol_native: 'дин.',
          decimal_digits: 0,
          rounding: 0,
          code: 'RSD',
          name_plural: 'Serbian dinars',
        },
        RUB: {
          symbol: 'RUB',
          name: 'Russian Ruble',
          symbol_native: 'руб.',
          decimal_digits: 2,
          rounding: 0,
          code: 'RUB',
          name_plural: 'Russian rubles',
        },
        RWF: {
          symbol: 'RWF',
          name: 'Rwandan Franc',
          symbol_native: 'FR',
          decimal_digits: 0,
          rounding: 0,
          code: 'RWF',
          name_plural: 'Rwandan francs',
        },
        SAR: {
          symbol: 'SR',
          name: 'Saudi Riyal',
          symbol_native: 'ر.س.‏',
          decimal_digits: 2,
          rounding: 0,
          code: 'SAR',
          name_plural: 'Saudi riyals',
        },
        SBD: {
          symbol: 'SI$',
          name: 'Solomon Islands Dollar',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'SBD',
          icon_name: 'sbd',
          name_plural: 'Solomon Islands Dollars',
        },
        SCR: {
          symbol: 'SRe',
          name: 'Seychellois Rupee',
          symbol_native: 'SR',
          decimal_digits: 2,
          rounding: 0,
          code: 'SCR',
          icon_name: 'scr',
          name_plural: 'Seychellois Rupees',
        },
        SDG: {
          symbol: 'SDG',
          name: 'Sudanese Pound',
          symbol_native: 'SDG',
          decimal_digits: 2,
          rounding: 0,
          code: 'SDG',
          name_plural: 'Sudanese pounds',
        },
        SEK: {
          symbol: 'Skr',
          name: 'Swedish Krona',
          symbol_native: 'kr',
          decimal_digits: 2,
          rounding: 0,
          code: 'SEK',
          name_plural: 'Swedish kronor',
        },
        SGD: {
          symbol: 'S$',
          name: 'Singapore Dollar',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'SGD',
          name_plural: 'Singapore dollars',
        },
        SHP: {
          symbol: '£',
          name: 'Saint Helena Pound',
          symbol_native: '£',
          decimal_digits: 2,
          rounding: 0,
          code: 'SHP',
          icon_name: 'shp',
          name_plural: 'Saint Helena Pounds',
        },
        SLL: {
          symbol: 'Le',
          name: 'Sierra Leonean Leone',
          symbol_native: 'Le',
          decimal_digits: 2,
          rounding: 0,
          code: 'SLL',
          icon_name: 'sll',
          name_plural: 'Sierra Leonean Leone',
        },
        SOS: {
          symbol: 'Ssh',
          name: 'Somali Shilling',
          symbol_native: 'Ssh',
          decimal_digits: 0,
          rounding: 0,
          code: 'SOS',
          name_plural: 'Somali shillings',
        },
        SRD: {
          symbol: '$',
          name: 'Surinamese Dollar',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'SRD',
          icon_name: 'srd',
          name_plural: 'Surinamese Dollar',
        },
        STD: {
          symbol: 'Db',
          name: 'São Tomé and Príncipe dobra',
          symbol_native: 'Db',
          decimal_digits: 2,
          rounding: 0,
          code: 'STD',
          name_plural: 'São Tomé and Príncipe dobras',
        },
        SVC: {
          symbol: '₡',
          name: 'Salvadoran Colón',
          symbol_native: '₡',
          decimal_digits: 2,
          rounding: 0,
          code: 'SVC',
          icon_name: 'svc',
          name_plural: 'Salvadoran Colón',
        },
        SYP: {
          symbol: 'SY£',
          name: 'Syrian Pound',
          symbol_native: 'ل.س.‏',
          decimal_digits: 0,
          rounding: 0,
          code: 'SYP',
          name_plural: 'Syrian pounds',
        },
        SZL: {
          symbol: 'L',
          name: 'Swazi Lilangeni',
          symbol_native: 'E‏',
          decimal_digits: 2,
          rounding: 0,
          code: 'SZL',
          icon_name: 'szl',
          name_plural: 'Swazi Lilangeni',
        },
        THB: {
          symbol: '฿',
          name: 'Thai Baht',
          symbol_native: '฿',
          decimal_digits: 2,
          rounding: 0,
          code: 'THB',
          name_plural: 'Thai baht',
        },
        TJS: {
          symbol: 'TJS',
          name: 'Tajikistani Somoni',
          symbol_native: 'TJS',
          decimal_digits: 2,
          rounding: 0,
          code: 'TJS',
          icon_name: 'tjs',
          name_plural: 'Tajikistani Somoni',
        },
        TMT: {
          symbol: 'T',
          name: 'Turkmenistani Manat',
          symbol_native: 'T‏',
          decimal_digits: 2,
          rounding: 0,
          code: 'TMT',
          icon_name: 'tmt',
          name_plural: 'Turkmenistani Manat',
        },
        TND: {
          symbol: 'DT',
          name: 'Tunisian Dinar',
          symbol_native: 'د.ت.‏',
          decimal_digits: 3,
          rounding: 0,
          code: 'TND',
          name_plural: 'Tunisian dinars',
        },
        TOP: {
          symbol: 'T$',
          name: 'Tongan Paʻanga',
          symbol_native: 'T$',
          decimal_digits: 2,
          rounding: 0,
          code: 'TOP',
          name_plural: 'Tongan paʻanga',
        },
        TRY: {
          symbol: 'TL',
          name: 'Turkish Lira',
          symbol_native: 'TL',
          decimal_digits: 2,
          rounding: 0,
          code: 'TRY',
          name_plural: 'Turkish Lira',
        },
        TTD: {
          symbol: 'TT$',
          name: 'Trinidad and Tobago Dollar',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'TTD',
          name_plural: 'Trinidad and Tobago dollars',
        },
        TWD: {
          symbol: 'NT$',
          name: 'New Taiwan Dollar',
          symbol_native: 'NT$',
          decimal_digits: 2,
          rounding: 0,
          code: 'TWD',
          name_plural: 'New Taiwan dollars',
        },
        TZS: {
          symbol: 'TSh',
          name: 'Tanzanian Shilling',
          symbol_native: 'TSh',
          decimal_digits: 0,
          rounding: 0,
          code: 'TZS',
          name_plural: 'Tanzanian shillings',
        },
        UAH: {
          symbol: '₴',
          name: 'Ukrainian Hryvnia',
          symbol_native: '₴',
          decimal_digits: 2,
          rounding: 0,
          code: 'UAH',
          name_plural: 'Ukrainian hryvnias',
        },
        UGX: {
          symbol: 'USh',
          name: 'Ugandan Shilling',
          symbol_native: 'USh',
          decimal_digits: 0,
          rounding: 0,
          code: 'UGX',
          name_plural: 'Ugandan shillings',
        },
        USD: {
          symbol: '$',
          name: 'US Dollar',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'USD',
          name_plural: 'US dollars',
        },
        UYU: {
          symbol: '$U',
          name: 'Uruguayan Peso',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'UYU',
          name_plural: 'Uruguayan pesos',
        },
        UZS: {
          symbol: 'UZS',
          name: 'Uzbekistan Som',
          symbol_native: 'UZS',
          decimal_digits: 0,
          rounding: 0,
          code: 'UZS',
          name_plural: 'Uzbekistan som',
        },
        VEF: {
          symbol: 'Bs.F.',
          name: 'Venezuelan Bolívar',
          symbol_native: 'Bs.F.',
          decimal_digits: 2,
          rounding: 0,
          code: 'VEF',
          name_plural: 'Venezuelan bolívars',
        },
        VND: {
          symbol: '₫',
          name: 'Vietnamese Dong',
          symbol_native: '₫',
          decimal_digits: 0,
          rounding: 0,
          code: 'VND',
          name_plural: 'Vietnamese dong',
        },
        VUV: {
          symbol: 'VUV',
          name: 'Vanuatu Vatu',
          symbol_native: 'VT',
          decimal_digits: 0,
          rounding: 0,
          code: 'VUV',
          icon_name: 'vuv',
          name_plural: 'Vanuatu Vatu',
        },
        WST: {
          symbol: 'WS$',
          name: 'Samoan Tala',
          symbol_native: 'T',
          decimal_digits: 2,
          rounding: 0,
          code: 'WST',
          icon_name: 'wst',
          name_plural: 'Samoan Tala',
        },
        XAF: {
          symbol: 'FCFA',
          name: 'CFA Franc BEAC',
          symbol_native: 'FCFA',
          decimal_digits: 0,
          rounding: 0,
          code: 'XAF',
          name_plural: 'CFA francs BEAC',
        },
        XAG: {
          symbol: 'XAG',
          name: 'Silver Ounce',
          symbol_native: 'XAG',
          decimal_digits: 2,
          rounding: 0,
          code: 'XAG',
          name_plural: 'Silver Ounces',
        },
        XAU: {
          symbol: 'XAU',
          name: 'Gold Ounce',
          symbol_native: 'XAU',
          decimal_digits: 2,
          rounding: 0,
          code: 'XAU',
          name_plural: 'Gold Ounces',
        },
        XCD: {
          symbol: 'EC$',
          name: 'East Caribbean Dollar',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'XCD',
          icon_name: 'xcd',
          name_plural: 'East Caribbean Dollars',
        },
        XDR: {
          symbol: 'SDR',
          name: 'Special drawing rights',
          symbol_native: 'SDR',
          decimal_digits: 2,
          rounding: 0,
          code: 'XDR',
          name_plural: 'Special drawing rights',
        },
        XOF: {
          symbol: 'CFA',
          name: 'CFA Franc BCEAO',
          symbol_native: 'CFA',
          decimal_digits: 0,
          rounding: 0,
          code: 'XOF',
          name_plural: 'CFA francs BCEAO',
        },
        XPF: {
          symbol: 'CFP',
          name: 'CFP Franc',
          symbol_native: 'CFP',
          decimal_digits: 0,
          rounding: 0,
          code: 'XPF',
          icon_name: 'xpf',
          name_plural: 'CFP francs',
        },
        YER: {
          symbol: 'YR',
          name: 'Yemeni Rial',
          symbol_native: 'ر.ي.‏',
          decimal_digits: 0,
          rounding: 0,
          code: 'YER',
          name_plural: 'Yemeni rials',
        },
        ZAR: {
          symbol: 'R',
          name: 'South African Rand',
          symbol_native: 'R',
          decimal_digits: 2,
          rounding: 0,
          code: 'ZAR',
          name_plural: 'South African rand',
        },
        ZMK: {
          symbol: 'ZK',
          name: 'Zambian Kwacha',
          symbol_native: 'ZK',
          decimal_digits: 0,
          rounding: 0,
          code: 'ZMK',
          name_plural: 'Zambian kwachas',
        },
        ZMW: {
          symbol: 'ZK',
          name: 'Zambian Kwacha',
          symbol_native: 'ZK',
          decimal_digits: 0,
          rounding: 0,
          code: 'ZMW',
          name_plural: 'Zambian kwachas',
        },
        ZWL: {
          symbol: 'ZWL',
          name: 'Zimbabwean dollar',
          symbol_native: '$',
          decimal_digits: 2,
          rounding: 0,
          code: 'ZWL',
          name_plural: 'Zimbabwean dollars',
        },
        BTC: {
          symbol: '₿',
          name: 'Bitcoin',
          symbol_native: '₿',
          decimal_digits: 8,
          rounding: 0,
          code: 'BTC',
          name_plural: 'Bitcoins',
        },
        ETH: {
          symbol: 'Ξ',
          name: 'Ethereum',
          symbol_native: 'Ξ',
          decimal_digits: 18,
          rounding: 0,
          code: 'ETH',
          name_plural: 'Ethereum',
        },
        BNB: {
          symbol: 'BNB',
          name: 'Binance',
          symbol_native: 'BNB',
          decimal_digits: 8,
          rounding: 0,
          code: 'BNB',
          name_plural: 'Binance',
        },
        XRP: {
          symbol: 'XRP',
          name: 'Ripple',
          symbol_native: 'XRP',
          decimal_digits: 6,
          rounding: 0,
          code: 'XRP',
          name_plural: 'Ripple',
        },
        SOL: {
          symbol: 'SOL',
          name: 'Solana',
          symbol_native: 'SOL',
          decimal_digits: 9,
          rounding: 0,
          code: 'SOL',
          name_plural: 'Solana',
        },
        DOT: {
          symbol: 'DOT',
          name: 'Polkadot',
          symbol_native: 'DOT',
          decimal_digits: 10,
          rounding: 0,
          code: 'DOT',
          name_plural: 'Polkadot',
        },
        AVAX: {
          symbol: 'AVAX',
          name: 'Avalanche',
          symbol_native: 'AVAX',
          decimal_digits: 18,
          rounding: 0,
          code: 'AVAX',
          name_plural: 'Avalanche',
        },
        MATIC: {
          symbol: 'MATIC',
          name: 'Matic Token',
          symbol_native: 'MATIC',
          decimal_digits: 18,
          rounding: 0,
          code: 'MATIC',
          name_plural: 'Matic Tokens',
        },
        LTC: {
          symbol: 'Ł',
          name: 'Litecoin',
          symbol_native: 'Ł',
          decimal_digits: 8,
          rounding: 0,
          code: 'LTC',
          name_plural: 'Litecoins',
        },
        ADA: {
          symbol: 'ADA',
          name: 'Cardano',
          symbol_native: 'ADA',
          decimal_digits: 6,
          rounding: 0,
          code: 'ADA',
          name_plural: 'Cardanos',
        },
      },
    };

    const promise = new Promise((res, reject) => {
      setTimeout(() => {
        return res(data);
      }, 1000);
    });

    const res = await promise;

    return res as any;

    // return promise.then((res) => res);
  }

  async latest({
    baseCurrency = '',
    currencies = [],
  }: {
    baseCurrency?: string;
    currencies?: string[];
  }) {
    const params = {
      base_currency: baseCurrency,
      currencies: currencies.join(','),
    };

    const data = {
      meta: {
        last_updated_at: '2023-02-21T23:59:59Z',
      },
      data: {
        ADA: {
          code: 'ADA',
          value: 2.543339,
        },
        AED: {
          code: 'AED',
          value: 3.673106,
        },
        AFN: {
          code: 'AFN',
          value: 89.329985,
        },
        ALL: {
          code: 'ALL',
          value: 108.055264,
        },
        AMD: {
          code: 'AMD',
          value: 393.804645,
        },
        ANG: {
          code: 'ANG',
          value: 1.803595,
        },
        AOA: {
          code: 'AOA',
          value: 507.50089,
        },
        ARS: {
          code: 'ARS',
          value: 193.114437,
        },
        AUD: {
          code: 'AUD',
          value: 1.457345,
        },
        AVAX: {
          code: 'AVAX',
          value: 0.047669,
        },
        AWG: {
          code: 'AWG',
          value: 1.802502,
        },
        AZN: {
          code: 'AZN',
          value: 1.700002,
        },
        BAM: {
          code: 'BAM',
          value: 1.836601,
        },
        BBD: {
          code: 'BBD',
          value: 2.020625,
        },
        BDT: {
          code: 'BDT',
          value: 106.282449,
        },
        BGN: {
          code: 'BGN',
          value: 1.836628,
        },
        BHD: {
          code: 'BHD',
          value: 0.37704,
        },
        BIF: {
          code: 'BIF',
          value: 2078.854428,
        },
        BMD: {
          code: 'BMD',
          value: 1.000001,
        },
        BNB: {
          code: 'BNB',
          value: 0.003206,
        },
        BND: {
          code: 'BND',
          value: 1.33927,
        },
        BOB: {
          code: 'BOB',
          value: 6.915364,
        },
        BRL: {
          code: 'BRL',
          value: 5.168008,
        },
        BSD: {
          code: 'BSD',
          value: 1.000734,
        },
        BTC: {
          code: 'BTC',
          value: 0.000041,
        },
        BTN: {
          code: 'BTN',
          value: 82.868346,
        },
        BWP: {
          code: 'BWP',
          value: 13.220358,
        },
        BYN: {
          code: 'BYN',
          value: 2.526014,
        },
        BYR: {
          code: 'BYR',
          value: 19600,
        },
        BZD: {
          code: 'BZD',
          value: 2.017244,
        },
        CAD: {
          code: 'CAD',
          value: 1.353542,
        },
        CDF: {
          code: 'CDF',
          value: 2045.002794,
        },
        CHF: {
          code: 'CHF',
          value: 0.927556,
        },
        CLF: {
          code: 'CLF',
          value: 0.029094,
        },
        CLP: {
          code: 'CLP',
          value: 802.791396,
        },
        CNY: {
          code: 'CNY',
          value: 6.873511,
        },
        COP: {
          code: 'COP',
          value: 4969.258451,
        },
        CRC: {
          code: 'CRC',
          value: 558.662697,
        },
        CUC: {
          code: 'CUC',
          value: 1.004954,
        },
        CUP: {
          code: 'CUP',
          value: 24.018638,
        },
        CVE: {
          code: 'CVE',
          value: 103.543143,
        },
        CZK: {
          code: 'CZK',
          value: 22.278042,
        },
        DJF: {
          code: 'DJF',
          value: 178.192018,
        },
        DKK: {
          code: 'DKK',
          value: 6.989749,
        },
        DOP: {
          code: 'DOP',
          value: 56.033388,
        },
        DOT: {
          code: 'DOT',
          value: 0.137533,
        },
        DZD: {
          code: 'DZD',
          value: 137.107213,
        },
        EGP: {
          code: 'EGP',
          value: 30.600834,
        },
        ERN: {
          code: 'ERN',
          value: 15.000021,
        },
        ETB: {
          code: 'ETB',
          value: 53.806649,
        },
        ETH: {
          code: 'ETH',
          value: 0.000602,
        },
        EUR: {
          code: 'EUR',
          value: 0.938821,
        },
        FJD: {
          code: 'FJD',
          value: 2.200303,
        },
        FKP: {
          code: 'FKP',
          value: 0.825903,
        },
        GBP: {
          code: 'GBP',
          value: 0.825851,
        },
        GEL: {
          code: 'GEL',
          value: 2.635003,
        },
        GGP: {
          code: 'GGP',
          value: 0.825904,
        },
        GHS: {
          code: 'GHS',
          value: 12.759946,
        },
        GIP: {
          code: 'GIP',
          value: 0.825903,
        },
        GMD: {
          code: 'GMD',
          value: 61.100067,
        },
        GNF: {
          code: 'GNF',
          value: 8611.260717,
        },
        GTQ: {
          code: 'GTQ',
          value: 7.823607,
        },
        GYD: {
          code: 'GYD',
          value: 211.161729,
        },
        HKD: {
          code: 'HKD',
          value: 7.844859,
        },
        HNL: {
          code: 'HNL',
          value: 24.671383,
        },
        HTG: {
          code: 'HTG',
          value: 149.395465,
        },
        HUF: {
          code: 'HUF',
          value: 359.575602,
        },
        IDR: {
          code: 'IDR',
          value: 15240.016594,
        },
        ILS: {
          code: 'ILS',
          value: 3.635564,
        },
        IMP: {
          code: 'IMP',
          value: 0.825903,
        },
        INR: {
          code: 'INR',
          value: 82.8616,
        },
        IQD: {
          code: 'IQD',
          value: 1460.65621,
        },
        IRR: {
          code: 'IRR',
          value: 42350.058936,
        },
        ISK: {
          code: 'ISK',
          value: 144.860254,
        },
        JEP: {
          code: 'JEP',
          value: 0.825903,
        },
        JMD: {
          code: 'JMD',
          value: 154.305091,
        },
        JOD: {
          code: 'JOD',
          value: 0.709401,
        },
        JPY: {
          code: 'JPY',
          value: 134.977236,
        },
        KES: {
          code: 'KES',
          value: 126.150252,
        },
        KGS: {
          code: 'KGS',
          value: 87.418247,
        },
        KHR: {
          code: 'KHR',
          value: 4078.229422,
        },
        KMF: {
          code: 'KMF',
          value: 462.850626,
        },
        KPW: {
          code: 'KPW',
          value: 899.946845,
        },
        KRW: {
          code: 'KRW',
          value: 1306.182201,
        },
        KWD: {
          code: 'KWD',
          value: 0.30655,
        },
        KYD: {
          code: 'KYD',
          value: 0.83396,
        },
        KZT: {
          code: 'KZT',
          value: 447.30176,
        },
        LAK: {
          code: 'LAK',
          value: 16866.54579,
        },
        LBP: {
          code: 'LBP',
          value: 15021.61711,
        },
        LKR: {
          code: 'LKR',
          value: 365.283598,
        },
        LRD: {
          code: 'LRD',
          value: 157.800312,
        },
        LSL: {
          code: 'LSL',
          value: 18.270023,
        },
        LTC: {
          code: 'LTC',
          value: 0.010641,
        },
        LTL: {
          code: 'LTL',
          value: 2.95274,
        },
        LVL: {
          code: 'LVL',
          value: 0.60489,
        },
        LYD: {
          code: 'LYD',
          value: 4.81436,
        },
        MAD: {
          code: 'MAD',
          value: 10.386612,
        },
        MATIC: {
          code: 'MATIC',
          value: 0.720737,
        },
        MDL: {
          code: 'MDL',
          value: 18.78961,
        },
        MGA: {
          code: 'MGA',
          value: 4289.163873,
        },
        MKD: {
          code: 'MKD',
          value: 57.858911,
        },
        MMK: {
          code: 'MMK',
          value: 2101.630887,
        },
        MNT: {
          code: 'MNT',
          value: 3526.999305,
        },
        MOP: {
          code: 'MOP',
          value: 8.085223,
        },
        MRO: {
          code: 'MRO',
          value: 356.999828,
        },
        MUR: {
          code: 'MUR',
          value: 46.65076,
        },
        MVR: {
          code: 'MVR',
          value: 15.350028,
        },
        MWK: {
          code: 'MWK',
          value: 1027.221973,
        },
        MXN: {
          code: 'MXN',
          value: 18.444919,
        },
        MYR: {
          code: 'MYR',
          value: 4.432508,
        },
        MZN: {
          code: 'MZN',
          value: 63.100111,
        },
        NAD: {
          code: 'NAD',
          value: 18.270034,
        },
        NGN: {
          code: 'NGN',
          value: 460.0009,
        },
        NIO: {
          code: 'NIO',
          value: 36.568753,
        },
        NOK: {
          code: 'NOK',
          value: 10.298417,
        },
        NPR: {
          code: 'NPR',
          value: 132.589518,
        },
        NZD: {
          code: 'NZD',
          value: 1.608897,
        },
        OMR: {
          code: 'OMR',
          value: 0.385039,
        },
        PAB: {
          code: 'PAB',
          value: 1.000734,
        },
        PEN: {
          code: 'PEN',
          value: 3.844049,
        },
        PGK: {
          code: 'PGK',
          value: 3.571634,
        },
        PHP: {
          code: 'PHP',
          value: 55.143056,
        },
        PKR: {
          code: 'PKR',
          value: 262.453494,
        },
        PLN: {
          code: 'PLN',
          value: 4.458555,
        },
        PYG: {
          code: 'PYG',
          value: 7339.435607,
        },
        QAR: {
          code: 'QAR',
          value: 3.641004,
        },
        RON: {
          code: 'RON',
          value: 4.619407,
        },
        RSD: {
          code: 'RSD',
          value: 110.160195,
        },
        RUB: {
          code: 'RUB',
          value: 74.650139,
        },
        RWF: {
          code: 'RWF',
          value: 1088.298881,
        },
        SAR: {
          code: 'SAR',
          value: 3.750861,
        },
        SBD: {
          code: 'SBD',
          value: 8.266733,
        },
        SCR: {
          code: 'SCR',
          value: 14.137229,
        },
        SDG: {
          code: 'SDG',
          value: 587.501173,
        },
        SEK: {
          code: 'SEK',
          value: 10.375637,
        },
        SGD: {
          code: 'SGD',
          value: 1.340306,
        },
        SHP: {
          code: 'SHP',
          value: 1.216752,
        },
        SLL: {
          code: 'SLL',
          value: 19750.036335,
        },
        SOL: {
          code: 'SOL',
          value: 0.039993,
        },
        SOS: {
          code: 'SOS',
          value: 568.500913,
        },
        SRD: {
          code: 'SRD',
          value: 33.524045,
        },
        STD: {
          code: 'STD',
          value: 20697.981008,
        },
        SVC: {
          code: 'SVC',
          value: 8.756536,
        },
        SYP: {
          code: 'SYP',
          value: 2512.53358,
        },
        SZL: {
          code: 'SZL',
          value: 18.2214,
        },
        THB: {
          code: 'THB',
          value: 34.655049,
        },
        TJS: {
          code: 'TJS',
          value: 10.713307,
        },
        TMT: {
          code: 'TMT',
          value: 3.510005,
        },
        TND: {
          code: 'TND',
          value: 3.152504,
        },
        TOP: {
          code: 'TOP',
          value: 2.342304,
        },
        TRY: {
          code: 'TRY',
          value: 18.867731,
        },
        TTD: {
          code: 'TTD',
          value: 6.791127,
        },
        TWD: {
          code: 'TWD',
          value: 30.499551,
        },
        TZS: {
          code: 'TZS',
          value: 2332.004505,
        },
        UAH: {
          code: 'UAH',
          value: 36.779994,
        },
        UGX: {
          code: 'UGX',
          value: 3692.865416,
        },
        USD: {
          code: 'USD',
          value: 1,
        },
        UYU: {
          code: 'UYU',
          value: 39.616178,
        },
        UZS: {
          code: 'UZS',
          value: 11328.880013,
        },
        VEF: {
          code: 'VEF',
          value: 2434563.23947,
        },
        VND: {
          code: 'VND',
          value: 23720.044673,
        },
        VUV: {
          code: 'VUV',
          value: 119.372654,
        },
        WST: {
          code: 'WST',
          value: 2.714388,
        },
        XAF: {
          code: 'XAF',
          value: 615.963599,
        },
        XAG: {
          code: 'XAG',
          value: 0.045726,
        },
        XAU: {
          code: 'XAU',
          value: 0.000545,
        },
        XCD: {
          code: 'XCD',
          value: 2.702553,
        },
        XDR: {
          code: 'XDR',
          value: 0.751888,
        },
        XOF: {
          code: 'XOF',
          value: 615.969189,
        },
        XPF: {
          code: 'XPF',
          value: 112.250167,
        },
        XRP: {
          code: 'XRP',
          value: 2.540362,
        },
        YER: {
          code: 'YER',
          value: 250.350271,
        },
        ZAR: {
          code: 'ZAR',
          value: 18.255321,
        },
        ZMK: {
          code: 'ZMK',
          value: 9001.2,
        },
        ZMW: {
          code: 'ZMW',
          value: 19.540192,
        },
        ZWL: {
          code: 'ZWL',
          value: 321.999592,
        },
      },
    };

    const promise = new Promise((res, reject) => {
      setTimeout(() => {
        return res(data);
      }, 1000);
    });

    const res = (await promise) as any;

    return {
      exchangeInfo: {
        [baseCurrency]: Object.values(res.data).map((x: any) => ({
          ...x,
          value: Math.random(),
        })),
      },
      lastUpdatedAt: res.meta.last_updated_at,
    } as any;

    // const { data } = await this.axiosInstance.get<GetExchangeRateResponse>(
    //   `/latest`,
    //   {
    //     params,
    //   },
    // );
    // const { data: exchange, meta } = data;

    // return {
    //   exchangeInfo: {
    //     [baseCurrency]: Object.values(exchange),
    //   },
    //   lastUpdatedAt: meta.last_updated_at,
    // };
  }
}

const currencyClient = new CurrencyApiClient();

export default currencyClient;
